### ISSUE TITLE
Not working with 21.0.2-graal and maven-3.9.6

### ISSUE THREAD

**Issue by alonsoir** [sivaprasadreddy/testcontainers-samples#127]
It is failing with this config:
┌<▪> ~/g/testcontainers-samples
└➤
java --version
java 21.0.2 2024-01-16 LTS
Java(TM) SE Runtime Environment Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30, mixed mode, sharing)
┌<▸> ~/g/testcontainers-samples
└➤
mvn --version
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: /Users/aironman/.sdkman/candidates/maven/current
Java version: 21.0.2, vendor: Oracle Corporation, runtime: /Users/aironman/.sdkman/candidates/java/21.0.2-graal
Default locale: es_ES, platform encoding: UTF-8
OS name: "mac os x", version: "14.2.1", arch: "x86_64", family: "mac"

┌<▸> ~/g/testcontainers-java-spring-boot-quickstart
└➤
./mvnw verify
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/3.1.3/spring-boot-starter-parent-3.1.3.pom
...
[INFO] Index file does not exist. Fallback to an empty index
[ERROR] Step 'palantir-java-format' found problem in 'src/test/java/demo/UserServiceTest.java':
'com.sun.tools.javac.tree.JCTree com.sun.tools.javac.tree.JCTree$JCImport.getQualifiedIdentifier()'
java.lang.NoSuchMethodError: 'com.sun.tools.javac.tree.JCTree com.sun.tools.javac.tree.JCTree$JCImport.getQualifiedIdentifier()'
    at com.palantir.javaformat.java.RemoveUnusedImports.getSimpleName (RemoveUnusedImports.java:245)
    at com.palantir.javaformat.java.RemoveUnusedImports.buildReplacements (RemoveUnusedImports.java:225)
    at com.palantir.javaformat.java.RemoveUnusedImports.removeUnusedImports (RemoveUnusedImports.java:209)
    at com.diffplug.spotless.glue.pjf.PalantirJavaFormatFormatterFunc.apply (PalantirJavaFormatFormatterFunc.java:42)
    at com.diffplug.spotless.FormatterFunc.apply (FormatterFunc.java:32)
    at com.diffplug.spotless.Jvm$Support$1.apply (Jvm.java:207)
    at com.diffplug.spotless.FormatterStepImpl$Standard.format (FormatterStepImpl.java:82)
    at com.diffplug.spotless.FormatterStep$Strict.format (FormatterStep.java:103)
    at com.diffplug.spotless.Formatter.compute (Formatter.java:246)
    at com.diffplug.spotless.PaddedCell.calculateDirtyState (PaddedCell.java:203)
    at com.diffplug.spotless.PaddedCell.calculateDirtyState (PaddedCell.java:190)
    at com.diffplug.spotless.maven.SpotlessCheckMojo.process (SpotlessCheckMojo.java:56)
    at com.diffplug.spotless.maven.AbstractSpotlessMojo.execute (AbstractSpotlessMojo.java:229)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:52)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:161)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:73)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] tc-basics 0.0.1-SNAPSHOT ........................... FAILURE [ 21.853 s]
[INFO] tc-testng 0.0.1-SNAPSHOT ........................... SKIPPED
[INFO] tc-dockerfile 0.0.1-SNAPSHOT ....................... SKIPPED
[INFO] tc-docker-compose 0.0.1-SNAPSHOT ................... SKIPPED
[INFO] spring-boot-jpa-demo 0.0.1-SNAPSHOT ................ SKIPPED
[INFO] spring-boot-redis-demo 0.0.1-SNAPSHOT .............. SKIPPED
[INFO] spring-boot-mongodb-demo 0.0.1-SNAPSHOT ............ SKIPPED
[INFO] spring-boot-kafka-demo 0.0.1-SNAPSHOT .............. SKIPPED
[INFO] spring-boot-rabbitmq-demo 0.0.1-SNAPSHOT ........... SKIPPED
[INFO] spring-boot-mockserver-demo 0.0.1-SNAPSHOT ......... SKIPPED
[INFO] spring-boot-wiremock-demo 0.0.1-SNAPSHOT ........... SKIPPED
[INFO] spring-boot-localstack-demo 1.0.0 .................. SKIPPED
[INFO] promotion-service 0.0.1-SNAPSHOT ................... SKIPPED
[INFO] product-service 0.0.1-SNAPSHOT ..................... SKIPPED
[INFO] spring-boot-microservices 1.0-SNAPSHOT ............. SKIPPED
[INFO] spring-boot-kotlin-demo 0.0.1-SNAPSHOT ............. SKIPPED
[INFO] quarkus-jpa-demo 1.0.0-SNAPSHOT .................... SKIPPED
[INFO] micronaut-jpa-demo 0.1 ............................. SKIPPED
[INFO] testcontainers-java-samples 0.0.1-SNAPSHOT ......... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:14 min
[INFO] Finished at: 2024-01-23T09:57:28+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.42.0:check (default) on project tc-basics: Execution default of goal com.diffplug.spotless:spotless-maven-plugin:2.42.0:check failed: An API incompatibility was encountered while executing com.diffplug.spotless:spotless-maven-plugin:2.42.0:check: java.lang.NoSuchMethodError: 'com.sun.tools.javac.tree.JCTree com.sun.tools.javac.tree.JCTree$JCImport.getQualifiedIdentifier()'
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.diffplug.spotless:spotless-maven-plugin:2.42.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/aironman/.m2/repository/com/diffplug/spotless/spotless-maven-plugin/2.42.0/spotless-maven-plugin-2.42.0.jar
[ERROR] urls[1] = file:/Users/aironman/.m2/repository/com/diffplug/spotless/spotless-lib/2.44.0/spotless-lib-2.44.0.jar
[ERROR] urls[2] = file:/Users/aironman/.m2/repository/com/diffplug/spotless/spotless-lib-extra/2.44.0/spotless-lib-extra-2.44.0.jar
[ERROR] urls[3] = file:/Users/aironman/.m2/repository/com/googlecode/concurrent-trees/concurrent-trees/2.6.1/concurrent-trees-2.6.1.jar
[ERROR] urls[4] = file:/Users/aironman/.m2/repository/dev/equo/ide/solstice/1.7.5/solstice-1.7.5.jar
[ERROR] urls[5] = file:/Users/aironman/.m2/repository/com/diffplug/durian/durian-swt.os/4.2.2/durian-swt.os-4.2.2.jar
[ERROR] urls[6] = file:/Users/aironman/.m2/repository/org/eclipse/platform/org.eclipse.osgi/3.18.300/org.eclipse.osgi-3.18.300.jar
[ERROR] urls[7] = file:/Users/aironman/.m2/repository/org/tukaani/xz/1.9/xz-1.9.jar
[ERROR] urls[8] = file:/Users/aironman/.m2/repository/com/squareup/okhttp3/okhttp/4.12.0/okhttp-4.12.0.jar
[ERROR] urls[9] = file:/Users/aironman/.m2/repository/com/squareup/okio/okio/3.6.0/okio-3.6.0.jar
[ERROR] urls[10] = file:/Users/aironman/.m2/repository/com/squareup/okio/okio-jvm/3.6.0/okio-jvm-3.6.0.jar
[ERROR] urls[11] = file:/Users/aironman/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-common/1.9.10/kotlin-stdlib-common-1.9.10.jar
[ERROR] urls[12] = file:/Users/aironman/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.8.21/kotlin-stdlib-jdk8-1.8.21.jar
[ERROR] urls[13] = file:/Users/aironman/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.8.21/kotlin-stdlib-1.8.21.jar
[ERROR] urls[14] = file:/Users/aironman/.m2/repository/org/jetbrains/annotations/13.0/annotations-13.0.jar
[ERROR] urls[15] = file:/Users/aironman/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.8.21/kotlin-stdlib-jdk7-1.8.21.jar
[ERROR] urls[16] = file:/Users/aironman/.m2/repository/com/diffplug/durian/durian-core/1.2.0/durian-core-1.2.0.jar
[ERROR] urls[17] = file:/Users/aironman/.m2/repository/com/diffplug/durian/durian-io/1.2.0/durian-io-1.2.0.jar
[ERROR] urls[18] = file:/Users/aironman/.m2/repository/com/diffplug/durian/durian-collect/1.2.0/durian-collect-1.2.0.jar
[ERROR] urls[19] = file:/Users/aironman/.m2/repository/org/codehaus/plexus/plexus-resources/1.2.0/plexus-resources-1.2.0.jar
[ERROR] urls[20] = file:/Users/aironman/.m2/repository/org/codehaus/plexus/plexus-utils/3.4.1/plexus-utils-3.4.1.jar
[ERROR] urls[21] = file:/Users/aironman/.m2/repository/org/eclipse/jgit/org.eclipse.jgit/6.7.0.202309050840-r/org.eclipse.jgit-6.7.0.202309050840-r.jar
[ERROR] urls[22] = file:/Users/aironman/.m2/repository/com/googlecode/javaewah/JavaEWAH/1.2.3/JavaEWAH-1.2.3.jar
[ERROR] urls[23] = file:/Users/aironman/.m2/repository/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
[ERROR] urls[24] = file:/Users/aironman/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by alonsoir** [comment]
If i disable spotless-maven-plugin in every project, verify phase succeed.

**Comment by sivaprasadreddy** [comment]
@alonsoir  Can you please check with the latest code?

**Comment by alonsoir** [comment]
sorry for the delay. 

[INFO] Reactor Summary:
[INFO]
[INFO] tc-basics 0.0.1-SNAPSHOT ........................... SUCCESS [ 21.652 s]
[INFO] tc-testng 0.0.1-SNAPSHOT ........................... SUCCESS [  5.102 s]
[INFO] tc-dockerfile 0.0.1-SNAPSHOT ....................... SUCCESS [ 10.113 s]
[INFO] tc-docker-compose 0.0.1-SNAPSHOT ................... SUCCESS [  0.747 s]
[INFO] spring-boot-jpa-demo 0.0.1-SNAPSHOT ................ SUCCESS [ 40.062 s]
[INFO] spring-boot-redis-demo 0.0.1-SNAPSHOT .............. SUCCESS [ 19.750 s]
[INFO] spring-boot-mongodb-demo 0.0.1-SNAPSHOT ............ SUCCESS [ 21.974 s]
[INFO] spring-boot-kafka-demo 0.0.1-SNAPSHOT .............. SUCCESS [ 25.241 s]
[INFO] spring-boot-rabbitmq-demo 0.0.1-SNAPSHOT ........... SUCCESS [ 33.871 s]
[INFO] spring-boot-mockserver-demo 0.0.1-SNAPSHOT ......... SUCCESS [ 10.497 s]
[INFO] spring-boot-wiremock-demo 0.0.1-SNAPSHOT ........... SUCCESS [ 31.756 s]
[INFO] spring-boot-localstack-demo 1.0.0 .................. SUCCESS [ 28.904 s]
[INFO] promotion-service 0.0.1-SNAPSHOT ................... SUCCESS [  4.076 s]
[INFO] product-service 0.0.1-SNAPSHOT ..................... SUCCESS [ 31.932 s]
[INFO] spring-boot-microservices 1.0-SNAPSHOT ............. SUCCESS [  0.010 s]
[INFO] spring-boot-kotlin-demo 0.0.1-SNAPSHOT ............. SUCCESS [ 13.533 s]
[INFO] quarkus-jpa-demo 1.0.0-SNAPSHOT .................... SUCCESS [ 16.659 s]
[INFO] micronaut-jpa-demo 0.1 ............................. SUCCESS [ 14.292 s]
[INFO] java-example 1.0-SNAPSHOT .......................... SUCCESS [  5.812 s]
[INFO] testcontainers-java-samples 0.0.1-SNAPSHOT ......... SUCCESS [  0.010 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:39 min
[INFO] Finished at: 2024-02-18T22:58:04+01:00
[INFO] ------------------------------------------------------------------------
[INFO] Test resources service already started on port 53170
[info] Shutting down Micronaut Test Resources service
